name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Midori Theme Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'midori-oceanwp.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
